mysql:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "nateyMahder@2022"
  database: "w3schools"
  
postgres:
  username: "postgres"
  password: "1234"
  dclass: "org.postgresql.Driver"
  url:  "jdbc:postgresql://localhost:5432/w3schools"
  